# This file is automatically generated by the build script.
# Fallback for local development
import os
import subprocess
from datetime import datetime, timedelta

import toml

TRIAL_MODE = True
LICENSE_EXPIRATION_DAYS = 1

# Always store dates as ISO format strings with UTC timezone
BUILD_DATE = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
expiration_dt = datetime.strptime(BUILD_DATE, "%Y-%m-%dT%H:%M:%SZ") + timedelta(days=LICENSE_EXPIRATION_DAYS)
EXPIRATION_DATE = expiration_dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def get_version():
    try:
        # Try to get the version from poetry
        version = subprocess.check_output(["poetry", "version", "-s"], stderr=subprocess.DEVNULL).decode().strip()
        if version:
            return version
    except Exception:
        pass
    # Try to get the version from pyproject.toml
    try:
        pyproject_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "pyproject.toml")
        with open(pyproject_path, "r") as f:
            pyproject = toml.load(f)
            return pyproject["project"]["version"]
    except Exception:
        pass
    # Fallback
    return "Unknown Version"


VERSION = get_version()
