# This file is automatically generated by the build script.
# Fallback for local development

import subprocess
from datetime import datetime, timedelta

TRIAL_MODE = True
LICENSE_EXPIRATION_DAYS = 1

# Always store dates as ISO format strings with UTC timezone
BUILD_DATE = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
expiration_dt = datetime.strptime(BUILD_DATE, "%Y-%m-%dT%H:%M:%SZ") + timedelta(days=LICENSE_EXPIRATION_DAYS)
EXPIRATION_DATE = expiration_dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def get_version():
    try:
        # Try to get the version from poetry
        version = subprocess.check_output(["poetry", "version", "-s"], stderr=subprocess.DEVNULL).decode().strip()
        if version:
            return version
    except Exception:
        pass

    # Fallback
    return "Unknown Version"


VERSION = get_version()
