"""Django settings for the stonks-overwatch project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from tzlocal import get_localzone

from stonks_overwatch.utils.core.demo_mode import is_demo_mode

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# This is the Project Root
PROJECT_PATH = BASE_DIR.parent.parent

DEFAULT_DATA_DIR = os.path.join(PROJECT_PATH, "data")
# Define the data directory
STONKS_OVERWATCH_DATA_DIR = os.environ.get("STONKS_OVERWATCH_DATA_DIR", DEFAULT_DATA_DIR)

# Define the cache directory
DEFAULT_CACHE_DIR = os.path.join(STONKS_OVERWATCH_DATA_DIR, "cache")
STONKS_OVERWATCH_CACHE_DIR = os.environ.get("STONKS_OVERWATCH_CACHE_DIR", DEFAULT_CACHE_DIR)

DEFAULT_LOGS_DIR = os.path.join(STONKS_OVERWATCH_DATA_DIR, "logs")
STONKS_OVERWATCH_LOGS_DIR = os.environ.get("STONKS_OVERWATCH_LOGS_DIR", DEFAULT_LOGS_DIR)


def ensure_data_directories():
    """
    Ensure all required data directories exist.

    This function is called after environment variables are set (e.g., by the Toga app)
    to create the necessary directories in platform-appropriate locations.

    IMPORTANT: This function reads environment variables directly instead of using
    module-level constants to ensure it gets the values set by the application,
    not the defaults computed at module import time.

    Raises:
        OSError: If directory creation fails (e.g., read-only file system)
    """
    import logging

    logger = logging.getLogger("stonks_overwatch.settings")

    # Read environment variables directly to get values set by the app
    # (not the module-level constants which were evaluated at import time)
    data_dir = os.environ.get("STONKS_OVERWATCH_DATA_DIR", DEFAULT_DATA_DIR)
    cache_dir = os.environ.get("STONKS_OVERWATCH_CACHE_DIR", os.path.join(data_dir, "cache"))
    logs_dir = os.environ.get("STONKS_OVERWATCH_LOGS_DIR", os.path.join(data_dir, "logs"))
    config_dir = os.environ.get("STONKS_OVERWATCH_CONFIG_DIR", os.path.join(data_dir, "config"))

    directories = [
        data_dir,
        cache_dir,
        logs_dir,
        config_dir,
    ]

    logger.info("Ensuring data directories exist...")
    logger.info(f"Data directory: {data_dir}")
    logger.info(f"Cache directory: {cache_dir}")
    logger.info(f"Logs directory: {logs_dir}")
    logger.info(f"Config directory: {config_dir}")

    for directory in directories:
        if not os.path.exists(directory):
            try:
                logger.info(f"Creating directory: {directory}")
                os.makedirs(directory, exist_ok=True, mode=0o755)
                logger.info(f"Successfully created directory: {directory}")
            except OSError as e:
                # Check if it's a read-only filesystem error
                if e.errno == 30:  # EROFS - Read-only file system
                    logger.error(
                        f"Failed to create directory '{directory}': Read-only file system. "
                        "This may occur in Flatpak/container environments. "
                        "The application should use XDG directories instead."
                    )
                    raise OSError(
                        f"Cannot create directory '{directory}' on read-only file system. "
                        "For Flatpak builds, ensure environment variables are set to use XDG directories."
                    ) from e

                # Provide detailed diagnostic information
                logger.error(f"Failed to create directory '{directory}': {e}")
                logger.error(
                    f"STONKS_OVERWATCH_DATA_DIR env var: {os.environ.get('STONKS_OVERWATCH_DATA_DIR', 'NOT SET')}"
                )
                logger.error(f"Current working directory: {os.getcwd()}")
                logger.error(f"__file__ path: {__file__}")
                logger.error(f"BASE_DIR: {BASE_DIR}")
                logger.error(f"PROJECT_PATH: {PROJECT_PATH}")

                raise OSError(
                    f"Failed to create directory '{directory}': {e}. "
                    f"This may indicate a read-only file system or insufficient permissions. "
                    "Environment variable STONKS_OVERWATCH_DATA_DIR: "
                    f"{os.environ.get('STONKS_OVERWATCH_DATA_DIR', 'NOT SET')}. "
                    f"Please check that the path is writable."
                ) from e
        else:
            logger.info(f"Directory already exists: {directory}")


STONKS_OVERWATCH_LOGS_FILENAME = "stonks-overwatch.log"

STONKS_OVERWATCH_SUPPORT_URL = "https://github.com/ctasada/stonks-overwatch/issues"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!2@us@&-4_p0s&k@u^s2xb865+yp=6-ic1e)*9o@$f=)66^ehi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_MODE = os.getenv("DEBUG_MODE", False) in [True, "true", "True", "1"]
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "stonks_overwatch.app_config.StonksOverwatchConfig",
    "django_extensions",
    "django_node_assets",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "stonks_overwatch.middleware.authentication.AuthenticationMiddleware",
    "stonks_overwatch.middleware.degiro_auth.DeGiroAuthMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
]

# Only use the custom error handler middleware in production/testing
if not DEBUG_MODE:
    MIDDLEWARE += [
        "stonks_overwatch.middleware.error_handler.CustomErrorHandlerMiddleware",
    ]

# Enable the profiler middleware if the PROFILE_MODE environment variable is set
PROFILE_MODE = os.getenv("PROFILE_MODE", False) in [True, "true", "True", "1"]
if PROFILE_MODE:
    MIDDLEWARE += ["pyinstrument.middleware.ProfilerMiddleware"]

ROOT_URLCONF = "stonks_overwatch.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
                "stonks_overwatch.context_processors.app_mode_processor",
                "stonks_overwatch.context_processors.version_processor",
                "stonks_overwatch.context_processors.support_url_processor",
                "stonks_overwatch.context_processors.appearance_processor",
                "stonks_overwatch.context_processors.demo_processor",
            ],
            # With the flattening of the prj structure, the auto register doesn't seem to work anymore.
            "libraries": {
                "custom_tags": "stonks_overwatch.templatetags.custom_tags",
            },
        },
    },
]

WSGI_APPLICATION = "stonks_overwatch.wsgi.application"

SESSION_COOKIE_AGE = 180 * 60  # 180 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Defines if the application will use the Demo DB or not
DEMO_MODE = is_demo_mode()

# Get database path dynamically from environment to support runtime configuration
# Read directly from environment instead of using module-level constants
_db_data_dir = os.environ.get("STONKS_OVERWATCH_DATA_DIR", DEFAULT_DATA_DIR)
_db_cache_dir = os.environ.get("STONKS_OVERWATCH_CACHE_DIR", os.path.join(_db_data_dir, "cache"))

# Define both databases - production and demo
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(_db_data_dir).resolve().joinpath("db.sqlite3"),
        "TEST": {
            "NAME": Path(_db_cache_dir).resolve().joinpath("test_db.sqlite3"),
        },
        "OPTIONS": {
            "timeout": 30,  # Increase timeout for database operations
            "init_command": """
                PRAGMA journal_mode = WAL;
                PRAGMA synchronous = NORMAL;
                PRAGMA temp_store = MEMORY;
                PRAGMA mmap_size = 268435456;
                PRAGMA busy_timeout = 30000;
            """,
        },
    },
    "demo": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(_db_data_dir).resolve().joinpath("demo_db.sqlite3"),
        "TEST": {
            "NAME": Path(_db_cache_dir).resolve().joinpath("test_demo_db.sqlite3"),
        },
        "OPTIONS": {
            "timeout": 30,
            "init_command": """
                PRAGMA journal_mode = WAL;
                PRAGMA synchronous = NORMAL;
                PRAGMA temp_store = MEMORY;
                PRAGMA mmap_size = 268435456;
                PRAGMA busy_timeout = 30000;
            """,
        },
    },
}

# Database router to select which database to use based on DEMO_MODE
DATABASE_ROUTERS = ["stonks_overwatch.utils.database.db_router.DatabaseRouter"]
# With the flattening of the prj structure, the auto register doesn't seem to work anymore.
MIGRATION_MODULES = {
    "stonks_overwatch": "stonks_overwatch.migrations",
}

TEST_RUNNER = "django.test.runner.DiscoverRunner"

# Needed because the AUTH framework is not used in this project
REST_FRAMEWORK = {"UNAUTHENTICATED_USER": None}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# Dynamically determine the system's timezone
TIME_ZONE = str(get_localzone())  # e.g., "Europe/Amsterdam" or "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "staticfiles"), os.path.join(PROJECT_PATH, "src", "icons")]

file_path = os.path.abspath(__file__)

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django_node_assets.finders.NodeModulesFinder",
    "django_node_assets.finders.ManifestNodeModulesFinder",
    "stonks_overwatch.utils.staticfiles_extra_finder.ExtraFilesFinder",
]

NODE_PACKAGE_JSON = os.path.join(PROJECT_PATH, "src", "package.json")
NODE_MODULES_ROOT = os.path.join(PROJECT_PATH, "src", "node_modules")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field


CACHES = {
    "default": {
        # FIXME: Disable caching for now so that we can see changes in the UI immediately. "Fixes" the Portfolio filter
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        # "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        # "LOCATION": "unique-snowflake",
    }
}

# Enable DEBUG logging only if DEBUG_MODE is set
STONKS_LOG_LEVEL = os.getenv("STONKS_LOG_LEVEL", "INFO").upper()
if DEBUG_MODE:
    STONKS_LOG_LEVEL = "DEBUG"

# Choose formatter based on environment - useful for development vs production
STONKS_LOG_FORMATTER = os.getenv("STONKS_LOG_FORMATTER", "verbose")
# Valid options: "verbose", "simple"


# Compute logging filename dynamically to handle environment variable changes
# Read environment variable directly instead of using module-level constant
def _get_log_filename():
    """Get log filename dynamically and ensure log directory exists.

    This function serves two purposes:
    1. Computes the log file path from environment variables
    2. Ensures the log directory exists (defensive programming)

    The directory creation is intentional here as a safety measure. Even though
    the application should create directories during initialization, this provides
    a fallback for cases where:
    - Settings are imported before app initialization
    - The logger is created in an unexpected order
    - Running in test/development environments

    Returns:
        str: Full path to the log file

    Note:
        Uses RotatingFileHandler with delay=True, so the file isn't created
        until the first log message is written.
    """
    import warnings

    # Read from environment to get runtime value, not import-time value
    logs_dir = os.environ.get("STONKS_OVERWATCH_LOGS_DIR")
    if not logs_dir:
        # Fallback: compute from data dir
        data_dir = os.environ.get("STONKS_OVERWATCH_DATA_DIR", DEFAULT_DATA_DIR)
        logs_dir = os.path.join(data_dir, "logs")

    # Ensure logs directory exists before returning the filename
    # This prevents FileNotFoundError when the logger tries to write
    try:
        os.makedirs(logs_dir, mode=0o755, exist_ok=True)
    except OSError as e:
        # Warn but continue - the logger will fail later with a clearer error
        warnings.warn(
            f"Failed to create log directory {logs_dir}: {e}. Logging may fail.",
            RuntimeWarning,
            stacklevel=2,
        )

    return os.path.join(logs_dir, STONKS_OVERWATCH_LOGS_FILENAME)


_log_filename = _get_log_filename()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": STONKS_LOG_FORMATTER,
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": _log_filename,
            "formatter": STONKS_LOG_FORMATTER,
            "maxBytes": 5 * 1024 * 1024,  # 5MB per file
            "backupCount": 5,  # Keeps the last 5 logs
            "encoding": "utf-8",
            "delay": True,  # Delay file creation until first write
        },
    },
    "loggers": {
        "apscheduler": {
            "handlers": ["console", "file"],
            "level": "WARN",
            "propagate": True,
        },
        "django": {
            "handlers": ["console", "file"],
            "level": "WARN",
            "propagate": True,
        },
        "django.db": {
            "handlers": ["console", "file"],
            "level": "WARN",
            "propagate": True,
        },
        "degiro_connector": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "stonks_overwatch": {
            "handlers": ["console", "file"],
            "level": STONKS_LOG_LEVEL,
            "propagate": False,
        },
    },
}
