# Generated by Django 5.1.4 on 2024-12-27 10:50

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeGiroCashMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=200)),
                ('balance_unsettled_cash', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('balance_flatex_cash', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('balance_cash_fund', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('balance_total', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('product_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('exchange_rate',
                        models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('order_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': '"degiro_cashmovements"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroCompanyProfile',
            fields=[
                ('isin', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': '"degiro_companyprofile"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroProductInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=8)),
                ('contract_size', models.DecimalField(decimal_places=1, max_digits=10)),
                ('product_type', models.CharField(max_length=25)),
                ('product_type_id', models.PositiveIntegerField()),
                ('tradable', models.BooleanField()),
                ('category', models.CharField(max_length=1)),
                ('currency', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('exchange_id', models.CharField(max_length=4)),
                ('only_eod_prices', models.BooleanField()),
                ('is_shortable', models.BooleanField(blank=True, default=None, null=True)),
                ('feed_quality', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('order_book_depth', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('vwd_identifier_type', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('vwd_id', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('quality_switchable', models.BooleanField(blank=True, default=None, null=True)),
                ('quality_switch_free', models.BooleanField(blank=True, default=None, null=True)),
                ('vwd_module_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('feed_quality_secondary', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('order_book_depth_secondary', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('vwd_identifier_type_secondary', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('vwd_id_secondary', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('quality_switchable_secondary', models.BooleanField(blank=True, default=None, null=True)),
                ('quality_switch_free_secondary', models.BooleanField(blank=True, default=None, null=True)),
                ('vwd_module_id_secondary', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': '"degiro_productinfo"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroProductQuotation',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('interval', models.CharField(max_length=10)),
                ('last_import', models.DateTimeField()),
                ('quotations', models.JSONField()),
            ],
            options={
                'db_table': '"degiro_productquotation"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroTransactions',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('product_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('buysell', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('counter_party', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('transfered', models.BooleanField()),
                ('fx_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('nett_fx_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gross_fx_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('auto_fx_fee_in_base_currency', models.DecimalField(decimal_places=10, max_digits=15)),
                ('total_in_base_currency', models.DecimalField(decimal_places=10, max_digits=15)),
                ('fee_in_base_currency',
                        models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('total_fees_in_base_currency', models.DecimalField(decimal_places=10, max_digits=15)),
                ('total_plus_fee_in_base_currency', models.DecimalField(decimal_places=10, max_digits=15)),
                ('total_plus_all_fees_in_base_currency', models.DecimalField(decimal_places=10, max_digits=15)),
                ('transaction_type_id', models.PositiveIntegerField()),
                ('trading_venue', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('executing_entity_id', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'db_table': '"degiro_transactions"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroAgendaDividend',
            fields=[
                ('event_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=25)),
                ('ric', models.CharField(max_length=16)),
                ('organization_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('country_code', models.CharField(max_length=4)),
                ('event_type', models.CharField(max_length=32)),
                ('ex_dividend_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('dividend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yield_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('market_cap', models.CharField(max_length=16)),
            ],
            options={
                'db_table': '"degiro_agendadividend"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroUpcomingPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_id', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_in_base_curr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_date', models.DateField()),
            ],
            options={
                'db_table': '"degiro_upcomingpayments"',
            },
        ),
    ]
