# Generated by Django 5.1.9 on 2025-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0002_yfinance"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBKRPosition",
            fields=[
                ("conid", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("acct_id", models.CharField(max_length=20)),
                ("contract_desc", models.CharField(max_length=8)),
                ("position", models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                (
                    "mkt_price",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "mkt_value",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                ("currency", models.CharField(max_length=3)),
                (
                    "avg_cost",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "avg_price",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "realized_pnl",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "unrealized_pnl",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_mkt_price",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_mkt_value",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_avg_cost",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_avg_price",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_realized_pnl",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                (
                    "base_unrealized_pnl",
                    models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
                ),  # noqa: E501
                ("asset_class", models.CharField(max_length=20)),
                ("listing_exchange", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=200)),
                ("group", models.CharField(default=None, max_length=200, null=True)),
                ("sector", models.CharField(default=None, max_length=200, null=True)),
                ("sector_group", models.CharField(default=None, max_length=200, null=True)),
                ("ticker", models.CharField(max_length=25)),
                ("type", models.CharField(max_length=25)),
                ("full_name", models.CharField(max_length=25)),
                ("is_us", models.BooleanField()),
            ],
            options={
                "db_table": '"ibkr_positions"',
            },
        ),
        migrations.CreateModel(
            name="IBKRTransactions",
            fields=[
                ("id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("acct_id", models.CharField(max_length=20)),
                ("conid", models.PositiveIntegerField()),
                ("date", models.DateTimeField()),
                ("cur", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True)),
                ("pr", models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True)),
                ("qty", models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True)),
                ("amt", models.DecimalField(decimal_places=10, max_digits=20)),
                ("type", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=200)),
            ],
            options={
                "db_table": '"ibkr_transactions"',
                "constraints": [
                    models.UniqueConstraint(fields=("date", "acct_id", "conid"), name="unique_transaction")
                ],
            },
        ),
    ]
