# Generated by Django 5.2.1 on 2025-06-02 05:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stonks_overwatch', '0002_yfinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeGiroAgendaDividend',
            fields=[
                ('event_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=25)),
                ('ric', models.CharField(max_length=16)),
                ('organization_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('country_code', models.CharField(max_length=4)),
                ('event_type', models.CharField(max_length=32)),
                ('ex_dividend_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('dividend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('yield_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('market_cap', models.CharField(max_length=16)),
            ],
            options={
                'db_table': '"degiro_agendadividend"',
            },
        ),
        migrations.CreateModel(
            name='DeGiroUpcomingPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_id', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_in_base_curr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_date', models.DateField()),
            ],
            options={
                'db_table': '"degiro_upcomingpayments"',
            },
        ),
    ]
