# Generated by Django 5.2.4 on 2025-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0003_ibkr"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitvavoBalance",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                (
                    "available",
                    models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
                ),
            ],
            options={
                "db_table": '"bitvavo_balance"',
            },
        ),
        migrations.CreateModel(
            name="BitvavoTransactions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                ("executed_at", models.DateTimeField()),
                ("type", models.CharField(max_length=20)),
                (
                    "price_currency",
                    models.CharField(blank=True, default=None, max_length=10, null=True),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "sent_currency",
                    models.CharField(blank=True, default=None, max_length=10, null=True),
                ),
                (
                    "sent_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "received_currency",
                    models.CharField(blank=True, default=None, max_length=10, null=True),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "fees_currency",
                    models.CharField(blank=True, default=None, max_length=10, null=True),
                ),
                (
                    "fees_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, default=None, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": '"bitvavo_transactions"',
            },
        ),
        migrations.CreateModel(
            name="BitvavoProductQuotation",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("interval", models.CharField(max_length=10)),
                ("last_import", models.DateTimeField()),
                ("quotations", models.JSONField()),
            ],
            options={
                "db_table": '"bitvavo_productquotation"',
            },
        ),
        migrations.CreateModel(
            name="BitvavoAssets",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default=None, max_length=100, null=True),
                ),
                ("decimals", models.IntegerField(default=0)),
                (
                    "deposit_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("deposit_confirmations", models.IntegerField(default=0)),
                ("deposit_status", models.CharField(max_length=20)),
                (
                    "withdrawal_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "withdrawal_min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=None,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("withdrawal_status", models.CharField(max_length=20)),
                ("networks", models.JSONField(blank=True, default=list, null=True)),
                (
                    "message",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": '"bitvavo_assets"',
            },
        ),
        migrations.CreateModel(
            name="BitvavoDepositHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("symbol", models.CharField(max_length=25)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "address",
                    models.CharField(blank=True, default=None, max_length=100, null=True),
                ),
                (
                    "payment_id",
                    models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
                ),
                (
                    "tx_id",
                    models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
                ),
                ("fee", models.DecimalField(decimal_places=10, max_digits=20)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": '"bitvavo_deposit_history"',
            },
        ),
    ]
