# Generated by Django 5.2.6 on 2025-09-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0005_brokers_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degirotransactions",
            name="quantity",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="degirotransactions",
            name="total",
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
