# Generated by Django 6.0.1 on 2026-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0007_reset_brokers_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibkrposition",
            name="asset_class",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="full_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="is_us",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="listing_exchange",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="ticker",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="ibkrposition",
            name="type",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
