# Generated by Django 6.0.1 on 2026-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0008_alter_ibkrposition_asset_class_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(help_text="Setting identifier", max_length=64, unique=True)),
                ("value", models.JSONField(help_text="Setting value (stored as JSON)")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Configuration",
                "verbose_name_plural": "Global Configurations",
                "db_table": '"global_configuration"',
            },
        ),
    ]
