# Generated by Django 6.0.1 on 2026-01-21 06:01
import datetime

import django.utils.timezone
from django.db import migrations, models

from stonks_overwatch.constants import BrokerName


def load_metatrader4_broker_config(apps, schema_editor):
    """Add MetaTrader 4 broker configuration to the database."""
    broker_configuration = apps.get_model("stonks_overwatch", "BrokersConfiguration")
    broker_configuration.objects.update_or_create(
        broker_name=BrokerName.METATRADER4,
        defaults={
            "enabled": False,
            "credentials": {},
            "start_date": datetime.date(2020, 1, 1),
            "update_frequency": 5,  # MT4 default is 5 minutes
        },
    )


def reverse_metatrader4_broker_config(apps, schema_editor):
    """Remove MetaTrader 4 broker configuration from the database."""
    broker_configuration = apps.get_model("stonks_overwatch", "BrokersConfiguration")
    broker_configuration.objects.filter(broker_name=BrokerName.METATRADER4).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("stonks_overwatch", "0010_brokersynclog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metatrader4Summary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When this record was created"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this record was last updated")),
                (
                    "account",
                    models.CharField(blank=True, help_text="Account number/identifier", max_length=100, null=True),
                ),
                ("currency", models.CharField(blank=True, help_text="Account currency", max_length=10, null=True)),
                (
                    "deposit_withdrawal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total deposits minus withdrawals",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "credit_facility",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Available credit facility", max_digits=15, null=True
                    ),
                ),
                (
                    "closed_trade_pl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Profit/Loss from closed trades",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "floating_pl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unrealized profit/loss from open positions",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Account balance", max_digits=15, null=True
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Account equity", max_digits=15, null=True
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Used margin", max_digits=15, null=True
                    ),
                ),
                (
                    "free_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Free margin", max_digits=15, null=True
                    ),
                ),
                ("raw_summary", models.JSONField(blank=True, help_text="Complete summary data from report", null=True)),
            ],
            options={
                "db_table": '"metatrader4_summary"',
                "indexes": [models.Index(fields=["updated_at"], name="metatrader4_updated_8a2bc4_idx")],
            },
        ),
        migrations.CreateModel(
            name="Metatrader4Trade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When this record was created"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this record was last updated")),
                ("ticket", models.CharField(help_text="MT4 ticket number", max_length=50, unique=True)),
                (
                    "open_time",
                    models.DateTimeField(blank=True, help_text="When position was opened or order placed", null=True),
                ),
                ("close_time", models.DateTimeField(blank=True, help_text="When position was closed", null=True)),
                (
                    "trade_type",
                    models.CharField(help_text="Type: buy, sell, balance, buy limit, sell stop, etc.", max_length=20),
                ),
                (
                    "size",
                    models.DecimalField(
                        blank=True, decimal_places=8, help_text="Position size/lots", max_digits=20, null=True
                    ),
                ),
                ("item", models.CharField(blank=True, help_text="Symbol/instrument", max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Order"), ("open", "Open Trade"), ("closed", "Closed Trade")],
                        default="pending",
                        help_text="Order/trade status: pending, open, or closed",
                        max_length=10,
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, help_text="Entry price", max_digits=20, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(blank=True, decimal_places=8, help_text="Exit price", max_digits=20, null=True),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, help_text="Current market price", max_digits=20, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, help_text="Stop loss level", max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, help_text="Take profit level", max_digits=20, null=True
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0.0, help_text="Commission charged", max_digits=15),
                ),
                ("taxes", models.DecimalField(decimal_places=2, default=0.0, help_text="Taxes charged", max_digits=15)),
                (
                    "swap",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="Swap/rollover charges", max_digits=15
                    ),
                ),
                ("profit", models.DecimalField(decimal_places=2, default=0.0, help_text="Profit/loss", max_digits=15)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description for balance/deposit entries", null=True),
                ),
                ("comment", models.TextField(blank=True, help_text="Order/trade comment", null=True)),
                ("raw_data", models.JSONField(blank=True, help_text="Original parsed row data", null=True)),
            ],
            options={
                "db_table": '"metatrader4_trade"',
                "indexes": [
                    models.Index(fields=["ticket"], name="metatrader4_ticket_404228_idx"),
                    models.Index(fields=["open_time"], name="metatrader4_open_ti_0470cf_idx"),
                    models.Index(fields=["close_time"], name="metatrader4_close_t_905717_idx"),
                    models.Index(fields=["item"], name="metatrader4_item_e00eca_idx"),
                    models.Index(fields=["trade_type"], name="metatrader4_trade_t_9d33bc_idx"),
                    models.Index(fields=["status"], name="metatrader4_status_26ca65_idx"),
                    models.Index(fields=["created_at"], name="metatrader4_created_bd0243_idx"),
                    models.Index(fields=["status", "item", "open_time"], name="mt4_status_item_time_idx"),
                    models.Index(fields=["status", "profit"], name="mt4_status_profit_idx"),
                    models.Index(fields=["trade_type", "open_time"], name="mt4_type_time_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("ticket",), name="unique_mt4_ticket"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["pending", "open"]), ("close_time__isnull", False), _connector="OR"
                        ),
                        name="closed_trades_have_close_time",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("trade_type", "balance"), ("size__gt", 0), _connector="OR"),
                        name="positive_trade_size",
                    ),
                ],
            },
        ),
        migrations.RunPython(load_metatrader4_broker_config, reverse_metatrader4_broker_config),
    ]
