# Generated by Django 5.0.1 on 2024-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovements',
            fields=[
                ('date', models.DateTimeField()),
                ('valueDate', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=3)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
