# Generated by Django 5.0.1 on 2024-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("degiro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveIntegerField()),
                ("date", models.DateTimeField()),
                ("buysell", models.CharField(max_length=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_type_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "counter_party",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                ("transfered", models.BooleanField()),
                ("fx_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("nett_fx_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("gross_fx_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "auto_fx_fee_in_base_currency",
                    models.DecimalField(decimal_places=10, max_digits=15),
                ),
                (
                    "total_in_base_currency",
                    models.DecimalField(decimal_places=10, max_digits=15),
                ),
                (
                    "fee_in_base_currency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_fees_in_base_currency",
                    models.DecimalField(decimal_places=10, max_digits=15),
                ),
                (
                    "total_plus_fee_in_base_currency",
                    models.DecimalField(decimal_places=10, max_digits=15),
                ),
                (
                    "total_plus_all_fees_in_base_currency",
                    models.DecimalField(decimal_places=10, max_digits=15),
                ),
                ("transaction_type_id", models.PositiveIntegerField()),
                (
                    "trading_venue",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                (
                    "executing_entity_id",
                    models.CharField(blank=True, default=None, max_length=30, null=True),
                ),
            ],
        ),
    ]
