# Generated by Django 5.0.2 on 2024-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degiro', '0002_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=8)),
                ('contractSize', models.DecimalField(decimal_places=1, max_digits=10)),
                ('productType', models.CharField(max_length=25)),
                ('productTypeId', models.PositiveIntegerField()),
                ('tradable', models.BooleanField()),
                ('category', models.CharField(max_length=1)),
                ('currency', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('exchangeId', models.CharField(max_length=4)),
                ('onlyEodPrices', models.BooleanField()),
                ('isShortable', models.BooleanField(blank=True, default=None, null=True)),
                ('feedQuality', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('orderBookDepth', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('vwdIdentifierType', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('vwdId', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('qualitySwitchable', models.BooleanField(blank=True, default=None, null=True)),
                ('qualitySwitchFree', models.BooleanField(blank=True, default=None, null=True)),
                ('vwdModuleId', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('feedQualitySecondary', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('orderBookDepthSecondary', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('vwdIdentifierTypeSecondary', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('vwdIdSecondary', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('qualitySwitchableSecondary', models.BooleanField(blank=True, default=None, null=True)),
                ('qualitySwitchFreeSecondary', models.BooleanField(blank=True, default=None, null=True)),
                ('vwdModuleIdSecondary', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
