# Generated by Django 5.0.2 on 2024-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("degiro", "0002_transactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("isin", models.CharField(max_length=25)),
                ("symbol", models.CharField(max_length=8)),
                ("contract_size", models.DecimalField(decimal_places=1, max_digits=10)),
                ("product_type", models.CharField(max_length=25)),
                ("product_type_id", models.PositiveIntegerField()),
                ("tradable", models.BooleanField()),
                ("category", models.CharField(max_length=1)),
                ("currency", models.CharField(max_length=3)),
                ("active", models.BooleanField()),
                ("exchange_id", models.CharField(max_length=4)),
                ("only_eod_prices", models.BooleanField()),
                ("is_shortable", models.BooleanField(blank=True, default=None, null=True)),
                ("feed_quality", models.CharField(blank=True, default=None, max_length=2, null=True)),
                ("order_book_depth", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("vwd_identifier_type", models.CharField(blank=True, default=None, max_length=16, null=True)),
                ("vwd_id", models.CharField(blank=True, default=None, max_length=32, null=True)),
                ("quality_switchable", models.BooleanField(blank=True, default=None, null=True)),
                ("quality_switch_free", models.BooleanField(blank=True, default=None, null=True)),
                ("vwd_module_id", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("feed_quality_secondary", models.CharField(blank=True, default=None, max_length=8, null=True)),
                ("order_book_depth_secondary", models.PositiveIntegerField(blank=True, default=None, null=True)),
                ("vwd_identifier_type_secondary", models.CharField(blank=True, default=None, max_length=8, null=True)),
                ("vwd_id_secondary", models.CharField(blank=True, default=None, max_length=16, null=True)),
                ("quality_switchable_secondary", models.BooleanField(blank=True, default=None, null=True)),
                ("quality_switch_free_secondary", models.BooleanField(blank=True, default=None, null=True)),
                ("vwd_module_id_secondary", models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
