# Generated by Django 5.0.2 on 2024-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degiro', '0003_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuotation',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quotations', models.JSONField()),
            ],
        ),
    ]
