# Generated by Django 5.1 on 2024-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("degiro", "0004_productquotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("isin", models.CharField(max_length=25, primary_key=True, serialize=False)),
                ("data", models.JSONField()),
            ],
        ),
    ]
